services:
  # 1. AI Agent Service (Python)
  - type: web
    name: smartaway-ai-service
    env: python
    plan: free
    repo: https://github.com/Ashish001123/SmartAway_AI
    branch: main
    rootDir: ai-agent
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false # Render will ask you to input this value

  # 2. Backend & Frontend Service (Node.js)
  - type: web
    name: smartaway-chat-app
    env: node
    plan: free
    repo: https://github.com/Ashish001123/SmartAway_AI
    branch: main
    buildCommand: npm run build
    startCommand: CLIENT_URL="https://$CLIENT_URL" AI_URL_PROD="https://$AI_URL_PROD/chat" npm run start
    envVars:
      - key: PORT
        value: 5002
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true # Render will automatically generate a secure secret
      - key: MONGODB_URI
        sync: false # Render will ask you to input this value
      - key: CLOUDINARY_CLOUD_NAME
        value: dnncir60c
      - key: CLOUDINARY_API_KEY
        value: "372112187682179"
      - key: CLOUDINARY_API_SECRET
        sync: false # Render will ask you to input this value
      # Fetch the raw hosts of the services and format them inside the startCommand
      - key: AI_URL_PROD
        fromService:
          type: web
          name: smartaway-ai-service
          property: host
      - key: CLIENT_URL
        fromService:
          type: web
          name: smartaway-chat-app
          property: host

